baseURL = "https://Krasn4ck.github.io"
languageCode = "en-us"
title = "Krasn4ck"
theme = "researcher"


[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

